### ISSUE TITLE
After adding the plugin, it does not appear

### ISSUE THREAD

**Issue by Druidblack** [Divi-0/Jellyfin.Plugin.Crunchyroll#1]
Good afternoon. After adding the link https://raw.githubusercontent.com/Divi-0/Jellyfin.Plugin.Crunchyroll/refs/heads/main/manifest.json and reloading, the plugin did not appear in the metadata section. jf 10.10.1
Which version of jf should the plugin work with?

**Comment by Divi-0** [comment]
Hi, yes thats correct (at least for now). I have not created a release yet, so there is no version that Jellyfin can find and download. It will probably be a few more days before I will create a Release for it. I still need to do some refactoring and movies aren't working yet, that's what I am currently working on. The documentation/wiki is also not final, there will be some changes.

**Comment by Druidblack** [comment]
Thanks for the reply. I will be waiting for the release version to try it.

**Comment by Divi-0** [comment]
Version 1.0.0 is now released, it should be available now for Jellyfin Version 10.10.3
