### ISSUE TITLE
Questions about the plugin's operation

### ISSUE THREAD

**Issue by Druidblack** [Divi-0/Jellyfin.Plugin.Crunchyroll#2]
The first thing I wanted to say is thank you for the work done.
After installing the plugin, the plugin image does not load
![654655](https://github.com/user-attachments/assets/3518d10c-9eba-444e-a5ae-701407a185d8)

I have a question about the logic of the plugin. Does the plugin work as a metadata provider, or is it just searching for the same names and downloading all the data, without a choice?

Now I have indicated the library in which I have posted several anime. I tried to get the anime title in Russian and English. And in both cases, I couldn't see the difference in the available data. The images were different from those that were on the preview on crunchyroll.

Is there a plug-in indicator?

**Comment by Divi-0** [comment]
For the logic: it uses the search api, that is used in the UI https://www.crunchyroll.com/search, the first result that contains the folder name of your series is used. If you have an anime in your collection, lets say videos/Black Clover/Season 01/..., it takes the folder name "Black Clover" to search via the search api.
It does search for every series in your collection, there is not option to select only single items.

For more details you can enable debug logging or also an indicator if it has searched for a specific series is to look into the metadata of that series, there should be a "ExternalId" for Crunchyroll, either empty or set

The missing image is interesting, maybe because its a svg, idk. I denfinitely saw it working, but I will check that

**Comment by Druidblack** [comment]
The plugin takes into account that when using https://www.crunchyroll.com/search when clicking on the link, it redirects me to https://www.crunchyroll.com/ru/search ?

The Russian language and the country of Russia are included in the settings of the media library.

The structure of my media library
A Terrified Teacher at Ghoul School! (2024) [TvdbId-443404]
 Season 1
   A Terrified Teacher at Ghoul School! - S01E01 - Welcome to Hyakki Academy!.mkv

By folder name (taking into account the year and id), the search shows the correct result first. But it may be possible for the plugin to ignore [TvdbId-443404] for TV series and [tmdbid-1858] for movies.These are recommendations from jf for a more accurate search.

I can't insert the entire folder name in the search bar : Banished From the Hero's Party, I Decided To Live a Quiet Life in the Countryside (2021) [TvdbId-400573]

Does the plugin have such a problem when searching?


And yet, when using the plugin, will it download all the data found and replace the existing ones?

  Now I have set up an image of my entire media library for anime and would like to receive only a description of the series and their name.

It is possible to manually select an image from themoviedb or crunchyroll?

**Comment by Divi-0** [comment]
That makes sence, ah yes I was a bit too focused on just names and forgot that folder names can have the years and ids for other metadata sources. The Season and episode name should be fine. I have to make some changes to the code to extract only the name, I guess. 

The plugin will store every metadata mentioned in the readme and overwrite everything (Images, Title, Description, Rating, ...) But thats a good idea to choose what you want to have. I will add it to the TODO list 👍I wanted everything 😂

> It is possible to manually select an image from themoviedb or crunchyroll?

No as I mentioned, it will just overwrite the current image. I don't even know if other plugins can do that, but if you know a plugin, let me know and I can have look on how I can implement that

**Comment by Druidblack** [comment]
I am really looking forward to the early implementation of selective loading. 

It often happens that the themoviedb and tvdb websites lack information about the series titles and episode descriptions.  I would like to get this information using the plugin.

P.S. In the meantime, I'll check version 1.0.1.

**Comment by Druidblack** [comment]
Good evening. I tried the plugin version 1.0.1. Nothing has changed for me in terms of data loading. In the plugin settings, I specified the name of the media library in which I have 4 anime series. I rebooted the server.  I have tried to enable scanning of new media data and full scan with image replacement. In both cases, I did not receive data from Crunchyroll.

https://logs.notifiarr.com/?35d1ada0ef29f288#FCvc7DAx3npBk9mRMA2czHADJj83AJsURp8SS68RxRVb  here is the log file of the last launch, if it can help in any way.

**Comment by Druidblack** [comment]
While the plugin is in the process of updating and adding functions, is it possible to add logging of actions to it so that you can see what the plugin is doing?

**Comment by Divi-0** [comment]
> While the plugin is in the process of updating and adding functions, is it possible to add logging of actions to it so that you can see what the plugin is doing?

Only errors are logged in default mode, you need to enable debug logging https://jellyfin.org/docs/general/administration/troubleshooting/#debug-logging

**Comment by Druidblack** [comment]
I see you've done a selective data upload. When can I expect a new version of the plugin?

**Comment by Divi-0** [comment]
First of all, thank you for testing. The version with feature select is now available with version 1.1.0 055543479f9412570f2497466df74f79701d1cee

I would like to close this issue now, to not create a big thread. If you still have any issues, let me now/create a new issue, with the specific question/error
