### ISSUE TITLE
Communication with the author of the plugin

### ISSUE THREAD

**Issue by Druidblack** [Divi-0/Jellyfin.Plugin.Crunchyroll#4]
Good afternoon. I tried the latest version of the plugin. The data began to load, but there are still issues that require either clarification or error correction.
Due to the fact that the API for themoviedb broke today, I could not correctly determine what caused the changes to the media libraries.

So I have a question. Is it possible to contact you (discord, for example) in order to promptly report errors found in the plugin.

To avoid creating new error messages.

**Comment by Druidblack** [comment]
1. After updating the plugin, the picture is still not displayed and the old version is shown.
when the update plugin is loaded, the version of the new plugin and the picture are displayed correctly.
![1111](https://github.com/user-attachments/assets/d7a1afd0-cab7-4df8-8355-d0ac6dbcd5e6)
2. After updating the plugin and restarting jf. The plugin settings did not select which data to upload. Only the library to scan was specified. After the restart. The plugin has updated all the data itself (completely) I didn't run the library scan.
![2222](https://github.com/user-attachments/assets/b6be81d5-57d0-4e4c-adc5-8b48dce95947)
P.S. To prevent overwriting of all data in all media libraries, it is probably worth doing so that specifying which media libraries to scan is mandatory.
4.But in those anime series where there was one season, the plugin transferred it to Specials

![33333](https://github.com/user-attachments/assets/a3d04919-adc3-4210-afb8-f3ad4113f343)

![444444](https://github.com/user-attachments/assets/5fc1a9f8-10b2-484f-950e-c0cb1bdcad2d)

![55555](https://github.com/user-attachments/assets/d6835a66-f424-4419-8c1c-ba42564f1ae9)

**Comment by Druidblack** [comment]
After scanning the media library and replacing all metadata, in order to return the data as it was before the plugin, the Specials library remains (which duplicates the data from the first season folder.
The plugin creates a Specials section referring to the folder of the first season. In fact, this is a duplication, but it can greatly spoil the library.
![45345](https://github.com/user-attachments/assets/51321459-4384-40cb-8c50-dab41b387561)

Deleted all the anime from the library. Then I added it again (selective data loading was already configured in the plugin.  The data loaded correctly (episode title and description) Nothing superfluous has loaded. 
P.S. Strange behavior of the plugin at the first launch after the update. You will need to check this behavior later when installing the latest version of the plugin on a new jf immediately.

**Comment by Druidblack** [comment]
After I scanned my media library from the anime (having received data from tmdb and tvdb), I decided to make a selective download of the data (episode title and series description.) https://www.crunchyroll.com / I didn't succeed. I tried to check the boxes to download the episode title and description, saved, scanned the library, tried to check all the boxes. I tried to reboot jf after saving the settings. But in any scenario, I was unable to retrieve the data again.

P.S. Maybe you can add a task to the scheduler that will start downloading data on a timer, or you can start it forcibly, for example after adding a new anime to the library.


p.s. After changing the plugin settings, you need to restart the jf server. It's very inconvenient. There is often no need to change the settings. But if it is necessary and there are a lot of people watching on the server, it may spoil the impression of the server or you will have to stop all views in order to apply the settings. Is it possible to apply the settings without restarting the server?

**Comment by Druidblack** [comment]
I understood.  running a scan of all media libraries, updated my data for the anime library.

It seems to me very inconvenient to add data to one library, update all libraries.
If the library is large, then it takes time.
![Безымянный](https://github.com/user-attachments/assets/e6c205e4-f303-4a70-aba7-8118070809dc)

**Comment by Druidblack** [comment]
![234323](https://github.com/user-attachments/assets/f15d5bba-c2ea-44d2-bf6a-75affe967560)

Do I understand correctly that if the plugin does not correctly match the data, then you can manually change the ID of the series in the metadata and use this data in the future so that the plugin loads the data correctly?

**Comment by Divi-0** [comment]
> 1. After updating the plugin, the picture is still not displayed and the old version is shown.
when the update plugin is loaded, the version of the new plugin and the picture are displayed correctly.

Can you look into the browser console & network tab, what url and error/response comes back? Also try with no cache option in network tab
<br>
> 2. After updating the plugin and restarting jf. The plugin settings did not select which data to upload. Only the library to scan was specified. After the restart. The plugin has updated all the data itself (completely) I didn't run the library scan.

To clarify, after updating it has done a full scan and updated every series, even though you did not selct anything in the configuration to update?
<br>
> P.S. To prevent overwriting of all data in all media libraries, it is probably worth doing so that specifying which media libraries to scan is mandatory.

At least for fresh installs it should not do anything, because the features are all disabled by default

> 4.But in those anime series where there was one season, the plugin transferred it to Specials

Can you post here the series/anime directory tree, so I can test it myself? Windows `tree /F` & Linux should be `tree -L`

**Comment by Divi-0** [comment]
> ![234323](https://private-user-images.githubusercontent.com/70659424/393537220-f15d5bba-c2ea-44d2-bf6a-75affe967560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1OTYzMTgsIm5iZiI6MTczMzU5NjAxOCwicGF0aCI6Ii83MDY1OTQyNC8zOTM1MzcyMjAtZjE1ZDViYmEtYzJlYS00NGQyLWJmNmEtNzVhZmZlOTY3NTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDE4MjY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MzEyMzY1OGE2NDQ1ZTQ5Mjk5NjYwYjczNmJmMTRkNTY4MGVhNjE2ZGZlMWU4MjVkNWMwOTY3ODViMTYyZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.leNw5IKhj5UUvlEwly9PSFhK8j1u_cIYUeCkx-btcmY)
> 
> Do I understand correctly that if the plugin does not correctly match the data, then you can manually change the ID of the series in the metadata and use this data in the future so that the plugin loads the data correctly?

Yes you can set the series Id manually and everything will work, `https://www.crunchyroll.com/series/GVDHX85QN/a-terrified-teacher-at-ghoul-school`

GVDHX85QN is the id, in the url

**Comment by Divi-0** [comment]
> I understood. running a scan of all media libraries, updated my data for the anime library.
> 
> It seems to me very inconvenient to add data to one library, update all libraries. If the library is large, then it takes time. ![Безымянный](https://private-user-images.githubusercontent.com/70659424/393536833-e6c205e4-f303-4a70-aba7-8118070809dc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1OTYzMTgsIm5iZiI6MTczMzU5NjAxOCwicGF0aCI6Ii83MDY1OTQyNC8zOTM1MzY4MzMtZTZjMjA1ZTQtZjMwMy00YTcwLWFiYTctODExODA3MDgwOWRjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDE4MjY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwOWQ3NWYxNDJmNDM1NWMxZTRiMGYwOTAxNTEzMTAxOWZhMWIyOWZmYzJmY2I2ZDIyY2UyYzU4YTQxMzVkNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EhNz8XWWPXpGjF0Z31euAh5CQ5yxluYvkeUrF55-ITc)

What exactly do you mean by that? Updating the folder structures, so the plugin can find the associated series on crunchyroll?

**Comment by Divi-0** [comment]
> After I scanned my media library from the anime (having received data from tmdb and tvdb), I decided to make a selective download of the data (episode title and series description.) https://www.crunchyroll.com / I didn't succeed. I tried to check the boxes to download the episode title and description, saved, scanned the library, tried to check all the boxes. I tried to reboot jf after saving the settings. But in any scenario, I was unable to retrieve the data again.

Would be interesting what the plugin has logged 

> P.S. Maybe you can add a task to the scheduler that will start downloading data on a timer, or you can start it forcibly, for example after adding a new anime to the library.

That's handled automatically by Jellyfin, the plugin is registered as a PostScan, so everytime a library scan from Jellyfin finished the crunchyroll plugin starts its work. That should include directory watchers from Jellyfin-Server, but I will check that.

> p.s. After changing the plugin settings, you need to restart the jf server. It's very inconvenient. There is often no need to change the settings. But if it is necessary and there are a lot of people watching on the server, it may spoil the impression of the server or you will have to stop all views in order to apply the settings. Is it possible to apply the settings without restarting the server?

Yes I am aware of that, it's unfortunately a bigger change than it's sounds like. Not a thing I could do in an hour, that will probably take some days to develop, have to refactor a few things. But I willing to change that

**Comment by Divi-0** [comment]
> Is it possible to contact you (discord, for example)

I am only partially available thru the day. For the sake of documentation it is also better to post the things here, so people with the same question/errors know it is already reported and I can reference those issues somewhere else. But I can also add a FAQ section.

**Comment by Druidblack** [comment]
> Can you look into the browser console & network tab, what url and error/response comes back?

![24244](https://github.com/user-attachments/assets/d888936e-e38c-4614-8c43-4e9ad8552a94)



> To clarify, after updating it has done a full scan and updated every series, even though you did not selct anything in the configuration to update?

Yes. He has updated all the data in the media library. The new plugin settings have not been enabled yet.I updated the plugin, rebooted jf. (scanning of the library is turned off after reboot). Subsequent jf reboots did not do this.

> At least for fresh installs it should not do anything, because the features are all disabled by default

This is logical. I didn't think about the fact that the plugin now has a selective download and if nothing is enabled, then nothing will load. Then everything works as it should.


> Can you post here the series/anime directory tree, so I can test it myself? Windows tree /F & Linux should be tree -L

Sorry, I don't understand what to do with these commands and where I need to enter them. I took a screenshot of the file browser.
Each folder additionally contains sound and video themes for anime, as well as in the folder with the series (season) there are subfolders with thumbnails for quick viewing when rewinding) I understand jf and the plugin ignores these folders when working.

![45645646](https://github.com/user-attachments/assets/b0ca7bff-7c32-42c5-84a5-bae88b3c0b3b)


> What exactly do you mean by that? Updating the folder structures, so the plugin can find the associated series on crunchyroll?

I have 4 media libraries of Anime, Movies, TV Series, and Music. The Anime media library is specified in the plugin settings, in which I want to get new data. To get new data, I have to do a full scan of all meditecs (TV series, movies and anime). So I asked, is it possible to scan only the Anime library, and not all of it, in order to get the data for the Anime library specified in the plugin settings?


> Would be interesting what the plugin has logged

When I wrote that when scanning the Anime library, no data was loaded. I didn't know yet that I needed to run a full scan of all media libraries. I'm getting all the data right now. By clicking on the button shown in the screenshot.
![435354354](https://github.com/user-attachments/assets/732789d6-4714-43dc-a917-fe1eb89b1493)



> Yes I am aware of that, it's unfortunately a bigger change than it's sounds like. Not a thing I could do in an hour, that will probably take some days to develop, have to refactor a few things. But I willing to change that

That was my suggestion. If it takes a lot of time, you can not do it or give it a low priority.



> I am only partially available thru the day. For the sake of documentation it is also better to post the things here, so people with the same question/errors know it is already reported and I can reference those issues somewhere else. But I can also add a FAQ section.

I understand your answer. Then I will continue to report here what I find.

**Comment by Druidblack** [comment]
I have added several new anime to my library. There was a question. 
Will the Crunchyroll ID be added when uploading any data (episode titles and description are included now)?

I noticed a strange behavior. The first matched (100%) anime were with a complete data replacement. Right now, I only have episode titles and episode descriptions in my settings. And the newly added anime could not be matched. Although they have the first place in the search on the site. 

After I sleep, I will check which set of uploaded data the plugin will be able to match the anime automatically.

I tried manually entering IDs. Everything works well in this regard. I added the ID and scanned the library. I got the data I need.

**Comment by Druidblack** [comment]
I started all over again.  I created a new library with anime, configured the plugin (settings in the screenshot), scanned the library.
![11111](https://github.com/user-attachments/assets/c3f494df-577a-4e3f-8e3b-9608051edbb7)
![222222](https://github.com/user-attachments/assets/7e9f7bf2-3b28-4c33-832e-e3b973835db5)

1. I was just lucky. The first four anime that I added to this library were correctly identified by the plugin.  But it's just luck.  I couldn't identify the rest of the anime that I added to the plugin.

Mysteria Friends (2019) [TvdbId-306111]
Mashle Magic and Muscles (2023) [TvdbId-421737]
Nanbaka (2016) [TvdbId-315103]
Skeleton Knight in Another World (2022) [TvdbId-401279]
Babylon (2019) (2019) [TvdbId-369143]

2. With the new library where the anime has only one season, there were no more problems with transferring it to the "special"
![454454545](https://github.com/user-attachments/assets/aab3232d-a77f-4fb9-97a9-864398ba1f55)
3. Now there is a new problem. In several anime, the plugin for one of the series does not add numbering, which is why one of the random series in jf is defined as the first. I'll try to show it in the screenshots
Alya Sometimes Hides Her Feelings in Russian (2024) [TvdbId-432531]
![444444](https://github.com/user-attachments/assets/f76c254d-05c7-47e0-b05f-69a996ff019c)
![33](https://github.com/user-attachments/assets/3731328a-b00e-459b-b387-61b6393a048b)

Banished From the Hero's Party, I Decided To Live a Quiet Life in the Countryside (2021) [TvdbId-400573]
![454545443444](https://github.com/user-attachments/assets/e2029a84-d6d7-4f12-b2f0-8a95e258d30e)
![fghhh](https://github.com/user-attachments/assets/bfe2712f-a4a0-4af3-a71f-3b469614554b)

The Magical Girl and the Evil Lieutenant Used to Be Archenemies (2024) [TvdbId-442367]
![35433](https://github.com/user-attachments/assets/fe6d5830-cb6a-461b-aa19-1229b59d5fb1)
![3443343434](https://github.com/user-attachments/assets/572df226-dc54-4782-bdc1-1376efd32052)

A Terrified Teacher at Ghoul School! (2024) [TvdbId-443404]
![6456456](https://github.com/user-attachments/assets/0a17c572-7d67-43e0-83a6-9c792b539a4d)
![534534534](https://github.com/user-attachments/assets/ed3bf52b-a794-4f87-88de-b936f93dee7f)

Repeated scanning of the library does not change the data. Everything remains the same. As I showed above.

**Comment by Druidblack** [comment]
Even when scanning, the plugin gives out some errors in the logs.

```
> [2024-12-08 15:31:55.022 +03:00] [INF] [169] Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.Login.LoginService: Anonymous Crunchyroll login was successful
> [2024-12-08 15:32:03.214 +03:00] [ERR] [173] Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.PostScan.CrunchyrollScan: An error occured during crunchyroll scan
> System.NotImplementedException: value 'Нравится' can not be converted
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.Comments.ExtractComments.HtmlCommentsExtractor.ConvertLikesToInt(String likes, CultureInfo language) in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/Comments/ExtractComments/HtmlCommentsExtractor.cs:line 145
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.Comments.ExtractComments.HtmlCommentsExtractor.ExtractCommentsFromHtml(String html, CultureInfo language) in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/Comments/ExtractComments/HtmlCommentsExtractor.cs:line 106
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.Comments.ExtractComments.HtmlCommentsExtractor.GetCommentsAsync(String url, CultureInfo language, CancellationToken cancellationToken) in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/Comments/ExtractComments/HtmlCommentsExtractor.cs:line 55
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.Comments.ExtractComments.ExtractCommentsCommandHandler.Handle(ExtractCommentsCommand request, CancellationToken cancellationToken) in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/Comments/ExtractComments/ExtractCommentsCommandHandler.cs:line 89
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.PostScan.ExtractCommentsTask.RunAsync(BaseItem episodeItem, CancellationToken cancellationToken) in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/PostScan/ExtractCommentsTask.cs:line 49
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.PostScan.SetEpisodeIdTask.RunPostTasks(BaseItem episodeItem, CancellationToken cancellationToken) in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/PostScan/SetEpisodeIdTask.cs:line 141
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.PostScan.SetEpisodeIdTask.<>c__DisplayClass5_0.<<RunAsync>b__0>d.MoveNext() in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/PostScan/SetEpisodeIdTask.cs:line 53
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.PostScan.SetEpisodeIdTask.RunAsync(BaseItem seasonItem, CancellationToken cancellationToken) in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/PostScan/SetEpisodeIdTask.cs:line 44
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.PostScan.SetSeasonIdTask.RunPostTasks(BaseItem item, CancellationToken cancellationToken) in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/PostScan/SetSeasonIdTask.cs:line 148
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.PostScan.SetSeasonIdTask.RunAsync(BaseItem seriesItem, CancellationToken cancellationToken) in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/PostScan/SetSeasonIdTask.cs:line 48
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.PostScan.SetTitleIdTask.RunPostTasks(BaseItem baseItem, CancellationToken cancellationToken) in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/PostScan/SetTitleIdTask.cs:line 90
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.PostScan.SetTitleIdTask.RunAsync(BaseItem item, CancellationToken cancellationToken) in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/PostScan/SetTitleIdTask.cs:line 42
>    at Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.PostScan.CrunchyrollScan.Run(IProgress`1 progress, CancellationToken cancellationToken) in /home/runner/work/Jellyfin.Plugin.Crunchyroll/Jellyfin.Plugin.Crunchyroll/src/Jellyfin.Plugin.Crunchyroll/Features/Crunchyroll/PostScan/CrunchyrollScan.cs:line 73
> [2024-12-08 15:32:16.718 +03:00] [INF] [113] Jellyfin.Plugin.Crunchyroll.Features.Crunchyroll.PostScan.CrunchyrollScan: CrunchyrollScan took "0:00:22.4462966"
```

**Comment by Druidblack** [comment]
The plugin does not turn off. In the case of plugins, if you click turn off the plugin, the waiting circle starts spinning. If you restart the page, the plugin remains enabled.

**Comment by Divi-0** [comment]
Hi I'm sorry for not responding the last days, I worked the last weeks, everyday, hard to make the plugin work like any other metadata provider. (Not as a PostScanTask anymore). I am burned out now, I can not see the project anymore 😅 The current state is still not stable but if you like you can build it yourself and install the plugin manually, just move the build output to the jellyfin plugins folder. I need a break from this project now. I will pick it up at a later point again

> The plugin does not turn off. In the case of plugins, if you click turn off the plugin, the waiting circle starts spinning. If you restart the page, the plugin remains enabled.

You can manually uninstall the plugin by going to your config folder of jellyfin `.../config/plugins` and then go to the plugins folder and remove the folder "Crunchyroll"

**Comment by Druidblack** [comment]
I'll try to figure out how to compile this project. But anyway, thanks for the work and I'll be waiting for inspiration to come back to you.
